GET http://localhost:3333/products

###
POST http://localhost:3333/products
Content-Type: application/json

{
    "name":"Livro DDD",
    "price": 80,
    "quantity": 5
}

###
POST http://localhost:3333/sessions
Content-Type: application/json

{
    "email":"leilafarias@gmail.com",
    "password": "teste12345"
}


###
POST http://localhost:3333/users
Content-Type: application/json

{
    "name":"Leila Farias",
    "email": "leilafarias@gmail.com",
    "password": "teste12345"
}

###
GET http://localhost:3333/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDY1OTc4ODMsImV4cCI6MTY0NjY4NDI4Mywic3ViIjoiZDcwNmYwMzQtOGFlNS00NDczLWEwZTQtNDY5NjI4NTljMGNmIn0.EgmiUVlH2XPJiOGnJr_o1Y7tESodkSB6BlAqfwhdXGk
###
POST http://localhost:3333/products
Content-Type: application/json

{

}

###
GET http://localhost:3333/products/750fe8b4-df2e-4dbc-a56a-3c1c66a56f48

###
PUT http://localhost:3333/products/750fe8b4-df2e-4dbc-a56a-3c1c66a56f48
Content-Type: application/json

{
    "name":"Livro DDD",
    "price": 80,
    "quantity": 4
}
###
DELETE http://localhost:3333/products/750fe8b4-df2e-4dbc-a56a-3c1c66a56f48

