GET http://localhost:3333/products

###
POST http://localhost:3333/products
Content-Type: application/json

{
    "name":"Livro DDD",
    "price": 80,
    "quantity": 5
}

###
POST http://localhost:3333/sessions
Content-Type: application/json

{
    "email":"leilafarias@gmail.com",
    "password": "teste12345"
}


###
POST http://localhost:3333/users
Content-Type: application/json

{
    "name":"Orlando Farias",
    "email": "landofarias@gmail.com",
    "password": "teste12345"
}

###
GET http://localhost:3333/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDcyMDk3MTUsImV4cCI6MTY0NzI5NjExNSwic3ViIjoiZDcwNmYwMzQtOGFlNS00NDczLWEwZTQtNDY5NjI4NTljMGNmIn0.RM0GfQBMlGy5Qzo-7-oz3q2ThVmLNwXcPAUWrEFldeo
###
POST http://localhost:3333/products
Content-Type: application/json

{

}

###
GET http://localhost:3333/products/750fe8b4-df2e-4dbc-a56a-3c1c66a56f48

###
PUT http://localhost:3333/products/750fe8b4-df2e-4dbc-a56a-3c1c66a56f48
Content-Type: application/json

{
    "name":"Livro DDD",
    "price": 80,
    "quantity": 4
}

###
PATCH http://localhost:3333/users/avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDcyMDk3MTUsImV4cCI6MTY0NzI5NjExNSwic3ViIjoiZDcwNmYwMzQtOGFlNS00NDczLWEwZTQtNDY5NjI4NTljMGNmIn0.RM0GfQBMlGy5Qzo-7-oz3q2ThVmLNwXcPAUWrEFldeo
Content-Type: multipart/form-data; boundary=X-RESTAPI-BOUNDARY
Accept: application/json

Content-Disposition: form-data; name="avatar"; filename="champions.png"

< .\champions.png

###
DELETE http://localhost:3333/products/750fe8b4-df2e-4dbc-a56a-3c1c66a56f48

###

POST http://localhost:3333/users/avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDcyMDk3MTUsImV4cCI6MTY0NzI5NjExNSwic3ViIjoiZDcwNmYwMzQtOGFlNS00NDczLWEwZTQtNDY5NjI4NTljMGNmIn0.RM0GfQBMlGy5Qzo-7-oz3q2ThVmLNwXcPAUWrEFldeo
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Accept: */*
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="champions.png"
Content-Type: image/png

< ./champions.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###


###
POST http://localhost:3333/password/forgot HTTP/1.1

Content-Type: application/json
{
    "email" : "landofarias@gmail.com"
}
